### ISSUE TITLE
Possible collaboration

### ISSUE THREAD

**Issue by brylie** [bulletshot60/kanbanzai#1]
Hi @bulletshot60. We are planning to develop a [project management platform](https://github.com/meteorcrowd/project-management) with Meteor, and would like to have a [Kanban board feature](https://github.com/meteorcrowd/project-management/issues/11) to visualize tasks. Would you be interested in collaborating with us on this open-source project?

**Comment by bulletshot60** [comment]
@brylie I, unfortunately, don't really have the time for collaboration due to other requirements, and I wrote this mainly just to learn the meteor platform.  The code is completely open source so you are free to take and incorporate anything I have anyway you see fit.  If you have any questions about the code base, I am more than happy to answer when I am able.

Thanks for reaching out, and sorry that I am unable to collaborate with you on your project.
